apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: vivek5151/netflix-clone:v3
        ports:
        - containerPort: 80
